import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Star from './components/Star';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className='signIn activeButton'>Sign In</h1>
        {children}
      </body>
    </html>
  )
}
